//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaladieAnimal
    {
        public int IdMA { get; set; }
        public int IdMaladie { get; set; }
        public int IdAnimal { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Maladie Maladie { get; set; }
    }
}
