//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduitFacture
    {
        public int IdProduitFacture { get; set; }
        public int IdFacture { get; set; }
        public int IdProduit { get; set; }
        public int Quantite { get; set; }
    
        public virtual Facture Facture { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
