//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.MaladieAnimal = new HashSet<MaladieAnimal>();
            this.AnimalRDV = new HashSet<AnimalRDV>();
            this.Ordonnance = new HashSet<Ordonnance>();
        }
    
        public int IdAnimal { get; set; }
        public string Nom { get; set; }
        public string NomEspece { get; set; }
        public string NomRace { get; set; }
        public Nullable<System.DateTime> DateDeNaissance { get; set; }
        public Nullable<int> Taille { get; set; }
        public Nullable<int> Poids { get; set; }
        public Nullable<int> IdClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaladieAnimal> MaladieAnimal { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalRDV> AnimalRDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance> Ordonnance { get; set; }
    }
}
