//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalRDV
    {
        public int IdARdv { get; set; }
        public int IdAnimal { get; set; }
        public int IdRDV { get; set; }
        public decimal Montant { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual RendezVous RendezVous { get; set; }
    }
}
