//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facture()
        {
            this.ProduitFacture = new HashSet<ProduitFacture>();
        }
    
        public int IdFacture { get; set; }
        public int NumeroFacture { get; set; }
        public System.DateTime DateFacture { get; set; }
        public Nullable<int> Montant { get; set; }
        public int IdClient { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProduitFacture> ProduitFacture { get; set; }
    }
}
