//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int IdLogs { get; set; }
        public int IdSalarie { get; set; }
        public System.DateTime DateConnexion { get; set; }
        public string actions { get; set; }
    
        public virtual Salarie Salarie { get; set; }
    }
}
