//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProduitOrdonnance
    {
        public int idProduitOrdonnance { get; set; }
        public int idProduit { get; set; }
        public int idOrdonnance { get; set; }
    
        public virtual Ordonnance Ordonnance { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
