//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veto.Screen.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendezVous
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendezVous()
        {
            this.AnimalRDV = new HashSet<AnimalRDV>();
            this.Ordonnance = new HashSet<Ordonnance>();
        }
    
        public int idRdv { get; set; }
        public int IdClient { get; set; }
        public System.TimeSpan heureDebut { get; set; }
        public System.TimeSpan heureFin { get; set; }
        public string motif { get; set; }
        public int IdJournee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimalRDV> AnimalRDV { get; set; }
        public virtual Client Client { get; set; }
        public virtual Journee Journee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance> Ordonnance { get; set; }
    }
}
